### PR TITLE
Projectsetup

### PR DESCRIPTION
**Pull request by ismail2009**
## Criteria
- [x] **Branch is up to date with master**
- [x] **The project runs**
- - [x] You can download and install locally, and run the project locally
- - [x] All existing and new features run without bugs
- - [x] The build script runs without error
- - [x] (If the project is already deployed to Heroku) the branch to be merged can deploy successfully to Heroku
- [x] **Code is consistent**
- - [x] Linter is used, no error messages
- - [x] Code is consistent with agreed team style
- - [x] Naming of files is consistent with project (e.g. all files named with camelCase)
- [x] **Tests are in place**
- - [x] Test file is in the same folder as the original file, with the extension .test.js
- - [x] Each new file written has a test file (where possible)
- [x] **Tests all pass**
- - [x] All tests should pass locally and on Travis
- - [x] Edge cases have been considered in tests
- [x] **Test coverage is maintained**
- - [x] Project coverage stays > 95%
- - [x] PR will not bring down coverage by more than 1%
- - [x] Files and lines of code have been ignored if they cannot be tested
- - [ ] If you are stuck with writing tests, you have assigned @arrested-developer to the PR and added a comment to explain what help is needed
- [x] **No console logs**
- - [x] Console.log is only used for crucial system messages (e.g. which port server is on).
- - [x] Any console.logs used for debugging have been removed.
- - [x] Console.error is used in error handling.
- - [x] global.console.log and global.console.error are mocked in tests when needed to avoid littering the console

### CODE REVIEW

**Comment by thejoefriel** [comment]
Hey @ismail2009 Travis issue looks like just a problem with eslint and the dependency tree. If you remove eslint from the root package.json you should be fine. You could put it then in the server package.json. To be extra safe, you can make sure you only have eslint 5.6.0 version installed, which is what we used for the server on our previous project. :)

**Comment by ismail2009** [comment]
@arrested-developer  can you review again

**Comment by arrested-developer** [comment]
Looks good! Great job with setting up testing and getting the coverage up.

The test settings in the server may test only files within the __test__ folder, however I have specified in the checklist that test files should be alongside the original file, i.e. a file like `myController.js` should have `myController.test.js` next to it in the same folder. The test regex may need changing for this, however you can do this later if needed.

I'm still confused about your eslint setup - I think the eslint dependencies should be moved from the parent repo to the server repo

Also you're 1 commit behind master on this branch so please make sure you've merged in the most recent master branch

**Comment by ismail2009** [comment]
@arrested-developer  can you check the pull request

**Pull request merged**
